apiVersion: v1
kind: Service
metadata:
  name: oauth-login-consent-service

spec:
  ports:
  - name: http
    port: 3000
    targetPort: oauth-port
  selector: 
    app: oauth-front
  type: ClusterIP
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-front-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: oauth-front
  template: 
    metadata: 
      labels: 
        app: oauth-front
    spec:
      containers:
      - name: oauth-front
        image: registry.gitlab.com/eco_system/oauth-login
        imagePullPolicy: IfNotPresent
        ports:
        - name: oauth-port
          containerPort: 5000
          
        envFrom:
        - configMapRef:
            name: oauth-front-env-configmap
        - secretRef:
            name: oauth-front-env-secrets

        resources:
          requests:
            cpu: 80m
            memory: 60Mi
          limits:
            cpu: 85m
            memory: 128Mi

      imagePullSecrets:
      - name: gitlab-auth

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-front-env-configmap
data:
  NODE_ENV: "development"
  PORT: "5000"
  MAINTENANCE_MODE: "false"
  
  # Logging
  ENABLE_STACKDRIVER: "false"
  ENABLE_CONSOLE_LOGS_IN_TEST: "true"

  # Services
  MAX_RETRIES: "30"
  RETRY_DURATION: "3000"

  SITE_NAME: "OAuth"
  DOMAIN: "isaiahwong.dev"
  OG_IMAGE: "/assets/images/bg.jpg"
  HYDRA_ADMIN_URL: "http://hydra-service.default.svc.cluster.local:9001"
  ACCOUNTS_SERVICE_ADDR: "api-accounts-v1-accountsservice.default.svc.cluster.local:5000"
  ACCOUNTS_SERVICE_DEADLINE: "10000" #10 sec
  PUBLIC_URL: "/auth"
  PRIMARY_COLOR: "#9FD9E1"
  SECONDARY_COLOR: "#000000"
  BORDER_COLOR: "#000000"
  LOGO_URL: "https://storage.googleapis.com/cander-assets/brand/cander.png"
  # GRPC_TRACE: "all"
  # GRPC_VERBOSITY: "DEBUG"